Update .chezmoi.toml Update .chezmoitemplates/env.zsh
Update .config/uwsm/env
Update .config/zsh/aliases
Change attributes of .config/uwsm/env-hyprland
Change attributes of .config/zsh/functions

diff --git a/private_dot_config/zsh/functions b/private_dot_config/zsh/functions
--- a/private_dot_config/zsh/functions
+++ b/private_dot_config/zsh/functions
@@ -42,6 +42,48 @@ function salias() {
     return 0
 }
 
+function prepend_path() {
+    if test -z "$1"; then
+        target="$PWD"
+    else
+        target=$(realpath "$1")
+    fi
+
+    if ! test -d "$target"; then
+        echo "$target not found"
+        return 1
+    fi
+
+    case ":$PATH:" in
+    *:"$target":*) ;;
+    *)
+        PATH="${target}${PATH:+:$PATH}"
+        ;;
+    esac
+    export PATH
+}
+
+function append_path() {
+    if test -z "$1"; then
+        target="$PWD"
+    else
+        target=$(realpath "$1")
+    fi
+
+    if ! test -d "$target"; then
+        echo "$target not found"
+        return 1
+    fi
+
+    case ":$PATH:" in
+    *:"$target":*) ;;
+    *)
+        PATH="${PATH:+$PATH:}${target}"
+        ;;
+    esac
+    export PATH
+}
+
 function y() {
     local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
     yazi "$@" --cwd-file="$tmp"
